### PR TITLE
fixed GCM setBody call

### PR DESCRIPTION
**Pull request by aporat**

### CODE REVIEW

**Comment by khrizt** [comment]
Thanks man!

**Comment by khrizt** [comment]
By the way, are you using the library? Any suggestion for improving? I'm doing unit tests right now and I hope to have them soon

**Comment by aporat** [comment]
yes. thank you for creating this library. im currently using the library for GCM notifications in production and it seems to be running well.

I tried setting up http2 for sending apns notifications, but gave up as there are alot of manual steps involved. I'll probably wait until curl ships with http2 built in. for that matter - I would suggest having a fallback for sending apns through standard http 1.1

**Comment by khrizt** [comment]
I understand but the http1.1 is deprecated by apple and I did this library just to be able to use apns with http2 :)

**Pull request merged**
